[package]
name = "blockchain"
version = "0.1.0"
authors = ["Isan-Rivkin <isanrivkin@gmail.com>"]

[dependencies]
time ="0.1.40"
serde ="1.0.78"
serde_derive = "1.0.78"
serde_json ="1.0.27"
sha2 ="0.7.1"